// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbt8vPNLLSh_WFhS9EU_SSE1akfo6JYc',
    appId: '1:935233337914:web:fd3d17f607dffa363d5303',
    messagingSenderId: '935233337914',
    projectId: 'taller-reparaciones-8cf11',
    authDomain: 'taller-reparaciones-8cf11.firebaseapp.com',
    storageBucket: 'taller-reparaciones-8cf11.firebasestorage.app',
    measurementId: 'G-RS1YWZ7QGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOhT_2Cb4-8chwmQqjIpIeMZT_WYQMro',
    appId: '1:935233337914:android:d7d3de6599c00ac23d5303',
    messagingSenderId: '935233337914',
    projectId: 'taller-reparaciones-8cf11',
    storageBucket: 'taller-reparaciones-8cf11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_U2hNwZYsVjZp3K4GtF6DAXb6bjoqq0',
    appId: '1:935233337914:ios:70aa982c4af991793d5303',
    messagingSenderId: '935233337914',
    projectId: 'taller-reparaciones-8cf11',
    storageBucket: 'taller-reparaciones-8cf11.firebasestorage.app',
    iosBundleId: 'com.example.tallerReparaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_U2hNwZYsVjZp3K4GtF6DAXb6bjoqq0',
    appId: '1:935233337914:ios:70aa982c4af991793d5303',
    messagingSenderId: '935233337914',
    projectId: 'taller-reparaciones-8cf11',
    storageBucket: 'taller-reparaciones-8cf11.firebasestorage.app',
    iosBundleId: 'com.example.tallerReparaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnbt8vPNLLSh_WFhS9EU_SSE1akfo6JYc',
    appId: '1:935233337914:web:c610f471230c14f23d5303',
    messagingSenderId: '935233337914',
    projectId: 'taller-reparaciones-8cf11',
    authDomain: 'taller-reparaciones-8cf11.firebaseapp.com',
    storageBucket: 'taller-reparaciones-8cf11.firebasestorage.app',
    measurementId: 'G-7BD36CVREG',
  );
}
